apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: networking-configuration-no-tls
  annotations:
    config.kubernetes.io/local-config: "true"

# Core networking resources
resources:
  - ../cilium-bgp-config.yaml
  # Network policies removed per security review - Hubble traffic flows correctly without them
  # - ../cilium/hubble-ui-netpol.yaml
  # - ../cilium/hubble-relay-netpol.yaml
  - hubble-relay-config-no-tls.yaml
  - hubble-relay-deployment-no-tls.yaml
  - hubble-ui-deployment-no-tls.yaml

# Common labels for networking resources
labels:
  - pairs:
      app.kubernetes.io/component: networking
      app.kubernetes.io/part-of: cilium-cni
      layer: networking
