# SECURITY NOTE: This is a TEMPLATE file only!
# Actual secrets should be managed via:
# 1. GitHub Actions secrets during CI/CD deployment
# 2. External Secret Operator with Vault integration
# 3. Manual kubectl application (NOT committed to git)

# This template shows the required secret structure but contains NO real values
apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secret
  namespace: github-actions
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/part-of: cicd
  annotations:
    # Mark this as a template to prevent accidental application
    config.kubernetes.io/local-config: "true"
type: Opaque
stringData:
  # GitHub Personal Access Token with repo, admin:org, workflow scopes
  # This will be populated by External Secret Operator or CI/CD pipeline
  github-token: "VAULT_SECRET_OR_PIPELINE_INJECTED"
  
  # Runner name pattern (will be suffixed with pod name for uniqueness)
  runner-name: "k8s-runner"
  
  # GitHub organization name
  github-org: "YOUR_GITHUB_ORG_NAME"