# SECURITY TEMPLATE: Grafana Admin Secret
# This is a TEMPLATE file - DO NOT commit real passwords!
# Manage via Vault or CI/CD pipeline secrets

apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: monitoring-stack
  annotations:
    # Mark as template to prevent accidental application
    config.kubernetes.io/local-config: "true"
type: Opaque
stringData:
  # Grafana admin password - will be injected by External Secret Operator or CI/CD
  admin-password: "VAULT_SECRET_OR_PIPELINE_INJECTED"
