# kustomization.yaml for monitoring stack
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitoring-stack
  annotations:
    config.kubernetes.io/local-config: "true"

# Monitoring stack resources
resources:
  - prometheus/prometheus-config.yaml
  - prometheus/prometheus-deployment.yaml
  - grafana/grafana-deployment.yaml
  - node-exporter/node-exporter.yaml
  - secrets/homeassistant-secret.yaml
  # Add more monitoring components as they're created
  # - alertmanager/alertmanager-deployment.yaml
  # Note: metrics-server is deployed separately as it requires kube-system namespace

# Common labels for all monitoring resources
commonLabels:
  environment: production
  layer: monitoring
  managed-by: kustomize
  cluster: kub

# Namespace for monitoring stack
namespace: monitoring

# Resource ordering
sortOptions:
  order: fifo
