apiVersion: v1
kind: ConfigMap
metadata:
  name: hubble-relay-config
  namespace: cilium
  labels:
    app.kubernetes.io/component: networking
    app.kubernetes.io/name: hubble-relay
    app.kubernetes.io/part-of: cilium-cni
    layer: networking
data:
  config.yaml: |
    peer-service: "hubble-peer.cilium.svc.kub-cluster.local:4244"
    listen-address: ":4245"
    metrics-listen-address: ":9966"
    pprof: true
    pprof-address: "localhost"
    pprof-port: 6061
    server-name: "relay.cilium.io"
    retry-timeout: 30s
    sort-buffer-len-max: 100
    sort-buffer-drain-timeout: 1s
    redact-enabled: false
    redact-http-headers-allow: ""
    redact-http-headers-deny: ""
    redact-http-url-query: false
    redact-kafka-api-key: false
    tls-disabled: true
