apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: networking-configuration
  annotations:
    config.kubernetes.io/local-config: "true"

# Core networking resources
resources:
  - cilium-bgp-config.yaml
  # Uncomment to deploy test loadbalancer for BGP verification
  # - test-loadbalancer.yaml
  # Multi-network examples are for reference - deploy manually if needed
  # - cilium-multi-network-examples.yaml

# Common labels for networking resources
labels:
  - pairs:
      app.kubernetes.io/component: networking
      app.kubernetes.io/part-of: cilium-cni
      layer: networking
