# Full Infrastructure Deployment RBAC for GitHub Actions Organization Runner
# Supports complete infrastructure-as-code deployment including Cilium, storage, monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: github-actions
  name: github-runner-minimal-role
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: cicd
rules:
# Allow full management of own namespace resources
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner-minimal-cluster-role
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: cicd
rules:
# Core Kubernetes resources for full infrastructure deployment
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]

# Storage management - CSI, persistent volumes, storage classes
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

# Networking - CNI, Cilium, ingress, network policies
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["cilium.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

# RBAC management (required for infrastructure deployment)
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

# Monitoring stack - Prometheus, Grafana, AlertManager
- apiGroups: ["monitoring.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["grafana.integreatly.org"]
  resources: ["*"]
  verbs: ["*"]

# Certificates and security
- apiGroups: ["cert-manager.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["security.istio.io"]
  resources: ["*"]
  verbs: ["*"]

# Custom Resource Definitions (required for operators)
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]

# Operators and admission controllers
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiregistration.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

# Policy and governance
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.istio.io"]
  resources: ["*"]
  verbs: ["*"]

# Metrics and autoscaling
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

# Cluster management
- apiGroups: ["coordination.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["node.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

# Events and logs
- apiGroups: ["events.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

# Scheduling
- apiGroups: ["scheduling.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

# Batch jobs
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-minimal-binding
  namespace: github-actions
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: cicd
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: github-actions
roleRef:
  kind: Role
  name: github-runner-minimal-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-minimal-cluster-binding
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: cicd
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: github-actions
roleRef:
  kind: ClusterRole
  name: github-runner-minimal-cluster-role
  apiGroup: rbac.authorization.k8s.io
