apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: github-actions
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/part-of: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: github-actions
  name: github-runner-role
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/part-of: cicd
rules:
# Allow reading secrets for deployment operations
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
# Allow reading configmaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
# Allow pod operations for deployment validation
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner-cluster-role
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/part-of: cicd
rules:
# Allow applying manifests across namespaces
- apiGroups: [""]
  resources: ["namespaces", "services", "configmaps"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "create", "update", "patch"]
# Monitoring resources
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-binding
  namespace: github-actions
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/part-of: cicd
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: github-actions
roleRef:
  kind: Role
  name: github-runner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-cluster-binding
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/part-of: cicd
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: github-actions
roleRef:
  kind: ClusterRole
  name: github-runner-cluster-role
  apiGroup: rbac.authorization.k8s.io