apiVersion: v1
kind: ServiceAccount
metadata:
  name: phoenix-runner
  namespace: github-actions
  labels:
    app.kubernetes.io/name: phoenix-runner
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/component: personal-repo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: github-actions
  name: phoenix-runner-role
  labels:
    app.kubernetes.io/name: phoenix-runner
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/component: personal-repo
rules:
# Allow reading secrets for deployment operations
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
# Allow reading configmaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
# Allow pod operations for deployment validation
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phoenix-runner-cluster-role
  labels:
    app.kubernetes.io/name: phoenix-runner
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/component: personal-repo
rules:
# Allow applying manifests across namespaces
- apiGroups: [""]
  resources: ["namespaces", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# Application deployments
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# RBAC for application service accounts
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# Storage resources
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# Autoscaling
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# Monitoring resources (if using Prometheus)
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# Custom Resource Definitions (for future extensibility)
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: phoenix-runner-binding
  namespace: github-actions
  labels:
    app.kubernetes.io/name: phoenix-runner
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/component: personal-repo
subjects:
- kind: ServiceAccount
  name: phoenix-runner
  namespace: github-actions
roleRef:
  kind: Role
  name: phoenix-runner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: phoenix-runner-cluster-binding
  labels:
    app.kubernetes.io/name: phoenix-runner
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/component: personal-repo
subjects:
- kind: ServiceAccount
  name: phoenix-runner
  namespace: github-actions
roleRef:
  kind: ClusterRole
  name: phoenix-runner-cluster-role
  apiGroup: rbac.authorization.k8s.io
