# filepath: /home/thomas/Repositories/personal/KubernetesLab/apps/production/github-runner.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-actions
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/component: runner
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/version: "2.321.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: github-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: github-runner
        app.kubernetes.io/component: runner
        app.kubernetes.io/part-of: cicd
    spec:
      serviceAccountName: github-runner
      securityContext:
        # Talos-compatible security contexts
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:2.321.0
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false  # GitHub runner needs write access
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: github-token
        - name: GITHUB_OWNER
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: github-org
        - name: RUNNER_NAME
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: runner-name
        - name: RUNNER_WORKDIR
          value: "/tmp/runner"
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        - name: RUNNER_SCOPE
          value: "org"
        - name: LABELS
          value: "kubernetes,talos,cilium,homelab,arm64"
        - name: EPHEMERAL
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: runner-work
          mountPath: /tmp/runner
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: tmp
          mountPath: /tmp
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "sleep 15"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep -v grep | grep Runner.Listener
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep -v grep | grep Runner.Listener
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: runner-work
        emptyDir:
          sizeLimit: 10Gi
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      nodeSelector:
        kubernetes.io/arch: arm64  # For Raspberry Pi CM4 nodes
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - github-runner
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
---
# Service for monitoring and debugging
apiVersion: v1
kind: Service
metadata:
  name: github-runner-svc
  namespace: github-actions
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: cicd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: github-runner
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
---
# HorizontalPodAutoscaler for dynamic scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: github-runner-hpa
  namespace: github-actions
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: cicd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: github-runner
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
---
# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: github-runner-pdb
  namespace: github-actions
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/component: pdb
    app.kubernetes.io/part-of: cicd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: github-runner