apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-path-storage

resources:
  - local-path-provisioner.yaml
  # Uncomment below for storage testing
  # - storage-test.yaml

# commonLabels removed to avoid selector immutability issues
# Labels will be added directly to the deployment template

patches:
  # Ensure proper node affinity for Pi nodes
  - target:
      kind: Deployment
      name: local-path-provisioner
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
