apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-test-pod
  namespace: default
  labels:
    app: storage-test
spec:
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534  
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: test-container
    image: busybox:1.35
    imagePullPolicy: Always
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: test-volume
      mountPath: /data
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
        ephemeral-storage: 100Mi
      limits:
        cpu: 200m
        memory: 128Mi
        ephemeral-storage: 200Mi
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: storage-test-pvc
  restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: storage-test-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: storage-test-job
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534  
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: test
        image: busybox:1.35
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          echo "Testing storage functionality..."
          echo "Current time: $(date)" > /data/test.txt
          echo "Writing test data to /data/test.txt"
          ls -la /data/
          cat /data/test.txt
          echo "Storage test completed successfully!"
        volumeMounts:
        - name: test-volume
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
            ephemeral-storage: 100Mi
          limits:
            cpu: 200m
            memory: 128Mi
            ephemeral-storage: 200Mi
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: storage-test-pvc
      restartPolicy: OnFailure
  backoffLimit: 3
---
# NetworkPolicy for storage test pod
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: storage-test-pod-netpol
  namespace: default
  labels:
    app: storage-test
spec:
  podSelector:
    matchLabels:
      app: storage-test
  policyTypes:
  - Ingress
  - Egress
  ingress: []  # No ingress needed for test pods
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
# NetworkPolicy for storage test job
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: storage-test-job-netpol
  namespace: default
  labels:
    app: storage-test-job
spec:
  podSelector:
    matchLabels:
      app: storage-test-job
  policyTypes:
  - Ingress
  - Egress
  ingress: []  # No ingress needed for test pods
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
